### ISSUE TITLE
invalid gvdb header

### ISSUE THREAD

**Issue by greenhand520** [lomirus/gtk-qq#37]
使用nightly buil通过后，但是运行`src/main.rs`出现下面错误
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { domain: g-resource-error-quark, code: 1, message: "invalid gvdb header" }', src/main.rs:39:47
stack backtrace:
   0:     0x560db49b84a0 - std::backtrace_rs::backtrace::libunwind::trace::heafe4e76b4fd4cac
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x560db49b84a0 - std::backtrace_rs::backtrace::trace_unsynchronized::h19321be3e640ae38
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560db49b84a0 - std::sys_common::backtrace::_print_fmt::h2fcd792e338f1cc5
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x560db49b84a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he5b28f0056e90af1
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x560db49dadfe - core::fmt::write::h8cee4989ef91009c
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/fmt/mod.rs:1202:17
   5:     0x560db49b31d5 - std::io::Write::write_fmt::h3fb743e9e09d846d
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/io/mod.rs:1679:15
   6:     0x560db49b9cd3 - std::sys_common::backtrace::_print::h751a1d130f5db246
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x560db49b9cd3 - std::sys_common::backtrace::print::h42eee5f5e3400273
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x560db49b9cd3 - std::panicking::default_hook::{{closure}}::hced954fcffb6800d
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:267:22
   9:     0x560db49b99bf - std::panicking::default_hook::hbc950bafaf526371
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:286:9
  10:     0x560db49ba379 - std::panicking::rust_panic_with_hook::ha913975239a26952
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:669:13
  11:     0x560db49ba277 - std::panicking::begin_panic_handler::{{closure}}::hd15d2ea30e523ac9
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:560:13
  12:     0x560db49b894c - std::sys_common::backtrace::__rust_end_short_backtrace::h991cb75202f3fe80
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x560db49b9f92 - rust_begin_unwind
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:556:5
  14:     0x560db3d3e2a3 - core::panicking::panic_fmt::hadf97da9eb1db8d0
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/panicking.rs:142:14
  15:     0x560db3d3e3f3 - core::result::unwrap_failed::h7567ca1ff620d57a
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/result.rs:1785:5
  16:     0x560db4138570 - core::result::Result<T,E>::unwrap::hd544b6b815296545
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/result.rs:1107:23
  17:     0x560db3f1cb08 - gtk_qq::init_resources::h82d09919be8e4455
                               at /home/user/Workspace/Projects/IdeaProjects/Rust/gtk-qq/src/main.rs:39:15
  18:     0x560db3f43e2b - gtk_qq::main::{{closure}}::hd3e8049f5786cc55
                               at /home/user/Workspace/Projects/IdeaProjects/Rust/gtk-qq/src/main.rs:24:5
  19:     0x560db3db7c5c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he945863fbdf58add
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/future/mod.rs:91:19
  20:     0x560db3f25df0 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::ha6766354cae7f373
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/park/thread.rs:263:54
  21:     0x560db3de2760 - tokio::coop::with_budget::{{closure}}::haba2863dbfdbdcf7
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
  22:     0x560db3d57680 - std::thread::local::LocalKey<T>::try_with::h854ab1ad37253422
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/thread/local.rs:445:16
  23:     0x560db3d56eed - std::thread::local::LocalKey<T>::with::h3752abb491a0b071
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/thread/local.rs:421:9
  24:     0x560db3f2580e - tokio::coop::with_budget::hf96e99983599dae4
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  25:     0x560db3f2580e - tokio::coop::budget::h7e4a2794295f390d
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  26:     0x560db3f2580e - tokio::park::thread::CachedParkThread::block_on::h56cbeed176b3f947
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/park/thread.rs:263:31
  27:     0x560db3efca72 - tokio::runtime::enter::Enter::block_on::hd4e50190375c5df0
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/enter.rs:151:13
  28:     0x560db3f19c4e - tokio::runtime::thread_pool::ThreadPool::block_on::h43a96a8dc0eb7033
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/mod.rs:81:9
  29:     0x560db3f42c5b - tokio::runtime::Runtime::block_on::h77e5c5d38621280f
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/mod.rs:477:43
  30:     0x560db3f1cc55 - gtk_qq::main::hc11e23b2831cb6f1
                               at /home/user/Workspace/Projects/IdeaProjects/Rust/gtk-qq/src/main.rs:34:5
  31:     0x560db3e55ceb - core::ops::function::FnOnce::call_once::hd92a2667723f18e6
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/ops/function.rs:251:5
  32:     0x560db3f8775e - std::sys_common::backtrace::__rust_begin_short_backtrace::hceed64cb09cef062
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/sys_common/backtrace.rs:122:18
  33:     0x560db3ecddf1 - std::rt::lang_start::{{closure}}::h9f4b24027cf4ca77
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/rt.rs:166:18
  34:     0x560db49aec7f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h43a13d8e353fa2cf
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/ops/function.rs:286:13
  35:     0x560db49aec7f - std::panicking::try::do_call::hb4ad2451f55ff841
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:464:40
  36:     0x560db49aec7f - std::panicking::try::h1c264415a2dcd70c
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:428:19
  37:     0x560db49aec7f - std::panic::catch_unwind::h5eaacebe4b60fd6f
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panic.rs:137:14
  38:     0x560db49aec7f - std::rt::lang_start_internal::{{closure}}::hd662914f4c894eea
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/rt.rs:148:48
  39:     0x560db49aec7f - std::panicking::try::do_call::h6d84bd1c7cfdfee7
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:464:40
  40:     0x560db49aec7f - std::panicking::try::h5135ff3079ab0e64
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panicking.rs:428:19
  41:     0x560db49aec7f - std::panic::catch_unwind::h831cf44434fdd677
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/panic.rs:137:14
  42:     0x560db49aec7f - std::rt::lang_start_internal::h4e9f2db716310b0b
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/rt.rs:148:20
  43:     0x560db3ecddca - std::rt::lang_start::hc47fb56fbb71ef33
                               at /rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/std/src/rt.rs:165:17
  44:     0x560db3f1ccf1 - main
  45:     0x7f3e7178b2d0 - <unknown>
  46:     0x7f3e7178b38a - __libc_start_main
  47:     0x560db3d3e5d5 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  48:                0x0 - <unknown>
```

我用的是idea 运行配置如图
![image](https://user-images.githubusercontent.com/32732204/192284192-d28c5bbf-bf0a-4a98-a46c-7b9bbcad4f84.png)
系统：manjaro linux内核5.15 gnome42

**Comment by lomirus** [comment]
你应该是 `builddir/assets/resources.gresource` 有问题，你是怎么生成这个文件的？你试试用文本编辑器打开，然后发一下其中的可读部分的内容看看。
